### ISSUE TITLE
Open To-Do's 12 September 

### ISSUE THREAD

**Issue by luciaeveberger** [lberger1993/chrisitinarberger.com#1]
## Outstanding Issues
- [ ] Make drawing page 
- [ ] Resize photos appropriately 
- [ ] Fix Container sizing on mobile 
- [ ] Test Cross Compatibility
